### ISSUE TITLE
Clean the front end 

### ISSUE THREAD

**Issue by AhmedElemary57** [Ahmedelsa3eed/A-simple-web-based-email-program#5]
# Frontend naming convention
* properties naming
* make the requests receive the error without problem 
  EX: when the password is wrong we should not make the response Accept that make no sense 
---
# Tasks
- [x] #7
- [x] #8
- [x] make use of register response endpoint
- [x] Send the current user email to inbox, sent, draft, contacts, trash endpoint
- [x] Send the id of the email to ``deleteFromInbox``, ``deleteFromDraft``, ``deleteFromSent`` endpoint
- [x] Delete referesh endpoint
